### PR TITLE
Add dependent repositories as submodules

### PR DESCRIPTION
**Pull request by mdellweg**
Activate use of galaxy_role_file (change in forklift needed).

[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
You might need to make the commit from https://github.com/theforeman/forklift/pull/908 available.

edit: Now merged upstream.

**Comment by mdellweg** [comment]
I didn't intend this, but the problem that forklift upstream was able to break pulplift is (i think) one reason more to use forklift as a submodule.

**Comment by CodeHeeler** [comment]
Thanks so much for this fix!  I've created an issue [0] for this work as it really helps us track changes for build and qe.  If you'd be so kind as to reference it instead of noissue in your commit, I'd really appreciate it.  Feel free to update the issue as you see fit if my description was inaccurate.

[0] https://pulp.plan.io/issues/4367

**Review by CodeHeeler — APPROVED** [review]

**Comment by asmacdo** [comment]
@mdellweg could you also update the docs for installation? Since you delete the setup script, I'm confused how this will work.

The setup script is also mentioned here: https://docs.pulpproject.org/en/3.0/nightly/contributing/dev-setup/index.html#developer-setup

IMO, the pulp docs should just say "Use the pulplift docs" and link so we don't need to tweak those docs when we make changes here. If you don't mind, could you update those docs as well? Alternatively, we could just file an issue to do that and go ahead and merge this.

**Pull request merged**
