### PR TITLE
Fix the long hostname issue more elegantly, and fix CI.

### PR DESCRIPTION
**Pull request by mikedep333**
Fix the long hostname issue more elegantly, and fix CI.

### CODE REVIEW

**Comment by mikedep333** [comment]
Only the FIPS tests are failing, and they're failing due to FIPS compatibiity issues in Pulp, so this is successful.

The long hostname issue was affecting every box but the debian ones.

**Review by fao89 — COMMENTED** [review]
could you explain to me how it is building the hostnames now?

**Comment by mikedep333** [comment]
> could you explain to me how it is building the hostnames now?

@fao89  The hostname is currently built as boxname.$(hostname -f) from the host's perspective.

So if your laptop is named fao89.home, pulp3-source-fedora32.fao89.home is under 64 chars.

But the Travis hostnames are very long. pulp3-source-fedora32.really.long.travis.on.gce.name will be over 64 chars.

**Comment by fao89** [comment]
thank you @mikedep333

**Review by fao89 — APPROVED** [review]

**Review by fao89 — APPROVED** [review]

**Pull request merged**
