### PR TITLE
bump ansible-pulp3

### PR DESCRIPTION
**Pull request by asmacdo**

### CODE REVIEW

**Comment by mdellweg** [comment]
I prefer to sum up what changed in the submodule or explain why it needs updating.
(in the commit message)

**Comment by asmacdo** [comment]
@mdellweg +1. Still getting used to submodule process, but that seems totally reasonable. Ill update that (in a bit, I'm currently on a different branch, and its testing.)

What I will be adding to the commit message is:
```

Incorporate changes from https://github.com/pulp/ansible-pulp3/pull/76
Fix multiple breaks
1. Create a user for molecule in the "source" scenario. This fix isn't
ideal-- we need to make more adjustments to the users generally, but
there were multiple problems with the direct approach. Ideally for a
dev install, the developer could simply set the `pulp_user` to their
user, which is expected to exist on the managed node. However this
approach broke the pulplift installation. I'm sure it will work, we just
need to try again when everything else is already working.

2. Minor fix: incorrect var name in pulp3-devel. Failure was hidden by
the first test failure.

3. Move collectstatic to handler. Multiple events cause static files to
be collected, so it makes more sense for this to be a handler. This
fixes idempotence tests, which again were hidden by the previous errors.
This was only an issue for installations that use the pulp3-devel role.
[noissue]
```

**Comment by mdellweg** [comment]
@asmacdo Think of future_austin doing `git log`. Put just enough information about the changes that you can decide whether it's worth visiting the submodule wtr to the problem you need to solve now.

**Review by CodeHeeler — APPROVED** [review]
I agree with the comment on a short commit here that's more topic headings, otherwise good to go as before.

**Pull request merged**
