### PR TITLE
Update pulp_installer

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by mikedep333** [comment]
I really don't want to merge this; this reverts a change I made to facilitate CI testing.

I want to constantly test the latest version of pulp_installer & other subrepos with pulplift CI, until we setup a bot or something.

It also makes it easier for devs to use pulp_installer.

Right now, it seems like if we accept this, we will have to constantly manually update pulplift's subrepos.

**Review by mikedep333 — CHANGES_REQUESTED** [review]
I really don't want to merge this; this reverts a change I made to facilitate CI testing.

I want to constantly test the latest version of pulp_installer & other subrepos with pulplift CI, until we setup a bot or something. So that pulplift nightly CI constantly tests whether pulp_installer and pulplift works with selinux for example. And I am working on pulp_installer SELinux now.

The instructions also makes it easier for devs to use pulp_installer.

Right now, it seems like if we accept this, we will have to constantly manually update pulplift's subrepos.

**Comment by mdellweg** [comment]
> I really don't want to merge this; this reverts a change I made to facilitate CI testing.

And that is why i wanted to wait until we are on the same page here.
 
> I want to constantly test the latest version of pulp_installer & other subrepos with pulplift CI, until we setup a bot or something. So that pulplift nightly CI constantly tests whether pulp_installer and pulplift works with selinux for example. And I am working on pulp_installer SELinux now.

To me that sounds like a goal that is best suited for the CI of pulp_installer itself. Because the moment something is tested here is already too late. If we can get (some of) those tasks to run on pull requests in the installer CI, we can catch mistakes before merging them into master. This repository only ever sees the installer post merge.

> The instructions also makes it easier for devs to use pulp_installer.

I tend to disagree, because with submodules pinned at certain commits, we provide our devs a tested and approved combination of Vagrantfile installer and tools. Forklift master breaking pulplift regularly without notice was the original reason to introduce it as a submodule in the first place. 

> Right now, it seems like if we accept this, we will have to constantly manually update pulplift's subrepos.

And that is the recommended workflow with submodules. Again, maybe the use of submodules as a tightly bound but still properly versioned relationship between projects has outlived its purpose here. Maybe pulplift has reached a state where we should rather pull the installer from galaxy.
`git submodule update --remote` is still a perfectly valid command to facilitate this manual update.

**Comment by mikedep333** [comment]
> > I really don't want to merge this; this reverts a change I made to facilitate CI testing.
> 
> And that is why i wanted to wait until we are on the same page here.
> 
> > I want to constantly test the latest version of pulp_installer & other subrepos with pulplift CI, until we setup a bot or something. So that pulplift nightly CI constantly tests whether pulp_installer and pulplift works with selinux for example. And I am working on pulp_installer SELinux now.
> 
> To me that sounds like a goal that is best suited for the CI of pulp_installer itself. Because the moment something is tested here is already too late. If we can get (some of) those tasks to run on pull requests in the installer CI, we can catch mistakes before merging them into master. This repository only ever sees the installer post merge.

That's true, and this will come when we merge into pulp_installer. But in the meantime, the nightly cronjob, and me clicking to re-run it, is the best we have.

Also, the main benefit of this repo is testing FIPS mode, and soon SELinux:
https://github.com/pulp/pulp_installer/pull/444

> 
> > The instructions also makes it easier for devs to use pulp_installer.
> 
> I tend to disagree, because with submodules pinned at certain commits, we provide our devs a tested and approved combination of Vagrantfile installer and tools.


When we do not update the submodules constantly though, I get lots of requests to update them. Devs wondering why they do not have the latest pulp_installer changes we made for them.

> Forklift master breaking pulplift regularly without notice was the original reason to introduce it as a submodule in the first place.

I was unaware of this. I never saw it happen since I started in Feb 2019.

> 
> > Right now, it seems like if we accept this, we will have to constantly manually update pulplift's subrepos.
> 
> And that is the recommended workflow with submodules. Again, maybe the use of submodules as a tightly bound but still properly versioned relationship between projects has outlived its purpose here. Maybe pulplift has reached a state where we should rather pull the installer from galaxy.
> `git submodule update --remote` is still a perfectly valid command to facilitate this manual update.

**Pull request closed without merging**
