### PR TITLE
Problem: no box for developing Pulp 2 to 3 migration

### PR DESCRIPTION
**Pull request by dkliban**
Solution: add 'pulp2-nightly-pulp3-source-centos7' box

[noissue]

### CODE REVIEW

**Comment by dkliban** [comment]
This is still a work in progress because the Pulp 2 install seems to be broken and nginx fails to start when httpd is already bound on port 80.

**Comment by dkliban** [comment]
This is no longer in progress. It does require the following changes to be merged: https://github.com/pulp/ansible-pulp/pull/128/

And the following Pulp 2 packaging issue needs to be resolved: https://pulp.plan.io/issues/5152

**Comment by bmbouter** [comment]
I got the submodule and vagrant up to work. I can confirm the I can see the status APIs of both environments. I was able to successfully sync pulp_file repo content and then pulp2 rpm content. AFAICT this is working perfectly!

**Review by bmbouter — APPROVED** [review]
This looks good to me!

**Pull request merged**
